#! /bin/sh

pkill -x sxhkd 
sxhkd

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio			0.5
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config pointer_follows_focus	true
bspc config focus_follows_pointer	true

# Border
bspc config focused_border_color	"#908f32"
bspc config normal_border_color		"#524a26"


#
# Autostart
#
# Set resolution
xrandr -s 1920x1080 &  
# If it doesn't work, maybe this mode doesn't exist, please, google "xrandr new mode"
# If you have different screen resolution please, change 

# Bar
pkill polybar
polybar left &
polybar right &
polybar middle &

# Wallpaper
feh --bg-tile ~/.config/wallpapers/krem-tiling.png &

# Cursor
xsetroot -cursor_name left_ptr &

# Clipboard
pkill clipit
clipit &
