#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
# prep -x flag means: matches eXact patter, in this case eXactly sxhkd
# we write the output to /dev/null because we don't need it
# if pgrep was unsuccesful then thing after || will be executed
# so, this command will startx sxhkd if no sxhkd was already running
# 
pkill -x sxhkd 
sxhkd

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"



#
# Autostart
#
# Set resolution
xrandr -s 1920x1080 &  
# If it doesn't work, maybe this mode doesn't exist, please, google "xrandr new mode"
# If you have different screen resolution please, change 


# Bar
pkill polybar
polybar left &
polybar middle &
polybar right &
# Wallpaper
feh --bg-scale ~/.config/wallpapers/wallpaper.png &

# Cursor
xsetroot -cursor_name left_ptr &
